export const GLOBALTYPES = {
  ALERT: "ALERT",
  PLAYER_CREATE: "PLAYER_CREATE",
  PLAYER_SUCCESS: "PLAYER_SUCCESS",
  PLAYER_FAILURE: "PLAYER_FAILURE",
  GETPLAYER_REQUEST: "GETPLAYER_REQUEST",
  GETPLAYER_SUCCESS: "GETPLAYER_SUCCESS",
  GETPLAYER_FAILURE: "GETPLAYER_FAILURE",
};
